#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qhull
Version  : 7.2.1
Release  : 1
URL      : https://github.com/qhull/qhull/archive/v7.2.1.tar.gz
Source0  : https://github.com/qhull/qhull/archive/v7.2.1.tar.gz
Summary  : A general dimension code for computing convex hulls and related structures
Group    : Development/Tools
License  : Qhull
Requires: qhull-bin = %{version}-%{release}
Requires: qhull-lib = %{version}-%{release}
Requires: qhull-license = %{version}-%{release}
Requires: qhull-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake

%description
Name
qhull, rbox         2015.2       2016/01/18

Convex hull, Delaunay triangulation, Voronoi diagrams, Halfspace intersection
Documentation:
html/index.htm
<http://www.qhull.org/html>

%package bin
Summary: bin components for the qhull package.
Group: Binaries
Requires: qhull-license = %{version}-%{release}

%description bin
bin components for the qhull package.


%package dev
Summary: dev components for the qhull package.
Group: Development
Requires: qhull-lib = %{version}-%{release}
Requires: qhull-bin = %{version}-%{release}
Provides: qhull-devel = %{version}-%{release}
Requires: qhull = %{version}-%{release}
Requires: qhull = %{version}-%{release}

%description dev
dev components for the qhull package.


%package doc
Summary: doc components for the qhull package.
Group: Documentation
Requires: qhull-man = %{version}-%{release}

%description doc
doc components for the qhull package.


%package lib
Summary: lib components for the qhull package.
Group: Libraries
Requires: qhull-license = %{version}-%{release}

%description lib
lib components for the qhull package.


%package license
Summary: license components for the qhull package.
Group: Default

%description license
license components for the qhull package.


%package man
Summary: man components for the qhull package.
Group: Default

%description man
man components for the qhull package.


%prep
%setup -q -n qhull-7.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1558942387
mkdir -p clr-build
pushd clr-build
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1558942387
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qhull
cp COPYING.txt %{buildroot}/usr/share/package-licenses/qhull/COPYING.txt
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qconvex
/usr/bin/qdelaunay
/usr/bin/qhalf
/usr/bin/qhull
/usr/bin/qvoronoi
/usr/bin/rbox

%files dev
%defattr(-,root,root,-)
/usr/include/libqhull/DEPRECATED.txt
/usr/include/libqhull/geom.h
/usr/include/libqhull/index.htm
/usr/include/libqhull/io.h
/usr/include/libqhull/libqhull.h
/usr/include/libqhull/mem.h
/usr/include/libqhull/merge.h
/usr/include/libqhull/poly.h
/usr/include/libqhull/qh-geom.htm
/usr/include/libqhull/qh-globa.htm
/usr/include/libqhull/qh-io.htm
/usr/include/libqhull/qh-mem.htm
/usr/include/libqhull/qh-merge.htm
/usr/include/libqhull/qh-poly.htm
/usr/include/libqhull/qh-qhull.htm
/usr/include/libqhull/qh-set.htm
/usr/include/libqhull/qh-stat.htm
/usr/include/libqhull/qh-user.htm
/usr/include/libqhull/qhull_a.h
/usr/include/libqhull/qset.h
/usr/include/libqhull/random.h
/usr/include/libqhull/stat.h
/usr/include/libqhull/user.h
/usr/include/libqhull_r/geom_r.h
/usr/include/libqhull_r/index.htm
/usr/include/libqhull_r/io_r.h
/usr/include/libqhull_r/libqhull_r.h
/usr/include/libqhull_r/mem_r.h
/usr/include/libqhull_r/merge_r.h
/usr/include/libqhull_r/poly_r.h
/usr/include/libqhull_r/qh-geom_r.htm
/usr/include/libqhull_r/qh-globa_r.htm
/usr/include/libqhull_r/qh-io_r.htm
/usr/include/libqhull_r/qh-mem_r.htm
/usr/include/libqhull_r/qh-merge_r.htm
/usr/include/libqhull_r/qh-poly_r.htm
/usr/include/libqhull_r/qh-qhull_r.htm
/usr/include/libqhull_r/qh-set_r.htm
/usr/include/libqhull_r/qh-stat_r.htm
/usr/include/libqhull_r/qh-user_r.htm
/usr/include/libqhull_r/qhull_ra.h
/usr/include/libqhull_r/qset_r.h
/usr/include/libqhull_r/random_r.h
/usr/include/libqhull_r/stat_r.h
/usr/include/libqhull_r/user_r.h
/usr/include/libqhullcpp/Coordinates.h
/usr/include/libqhullcpp/PointCoordinates.h
/usr/include/libqhullcpp/Qhull.h
/usr/include/libqhullcpp/QhullError.h
/usr/include/libqhullcpp/QhullFacet.h
/usr/include/libqhullcpp/QhullFacetList.h
/usr/include/libqhullcpp/QhullFacetSet.h
/usr/include/libqhullcpp/QhullHyperplane.h
/usr/include/libqhullcpp/QhullIterator.h
/usr/include/libqhullcpp/QhullLinkedList.h
/usr/include/libqhullcpp/QhullPoint.h
/usr/include/libqhullcpp/QhullPointSet.h
/usr/include/libqhullcpp/QhullPoints.h
/usr/include/libqhullcpp/QhullQh.h
/usr/include/libqhullcpp/QhullRidge.h
/usr/include/libqhullcpp/QhullSet.h
/usr/include/libqhullcpp/QhullSets.h
/usr/include/libqhullcpp/QhullStat.h
/usr/include/libqhullcpp/QhullVertex.h
/usr/include/libqhullcpp/QhullVertexSet.h
/usr/include/libqhullcpp/RboxPoints.h
/usr/include/libqhullcpp/RoadError.h
/usr/include/libqhullcpp/RoadLogEvent.h
/usr/include/libqhullcpp/RoadTest.h
/usr/include/libqhullcpp/functionObjects.h
/usr/lib64/libqhull.so
/usr/lib64/libqhull_p.so
/usr/lib64/libqhull_r.so

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/qhull/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libqhull.so.7
/usr/lib64/libqhull.so.7.2.0
/usr/lib64/libqhull_p.so.7
/usr/lib64/libqhull_p.so.7.2.0
/usr/lib64/libqhull_r.so.7
/usr/lib64/libqhull_r.so.7.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qhull/COPYING.txt

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/qhull.1
/usr/share/man/man1/rbox.1
